#!/bin/bash

usage(){
    exec 1>&2
    echo "Usage: $0 [option] [word]"
    echo "It will help you look up Bing for the word and show it up."
    echo "Options:"
    echo "      -h      Show this message and exit."
    echo "      -c      Show how many words (lines) are stored."
    echo "      -a      For debug use."
    echo "      -y      Look up youdao instead of Bing."
    echo "      {word}  Do a quick search of {word} and exit."
    echo
    echo "You can use $0 without option to start the interactive mode."
}

random_color(){
    g=$(($RANDOM % 200 + 56))
    f=$(($RANDOM % 200 + 56))
    b=$(($RANDOM % 200 + 56))
    echo -en "\e[38;2;${f};${g};${b}m"
}

seperate_line(){
    col=`tput cols`
    for i in `seq $col`; do echo -n "-"; done
    echo
}

search_save(){
    METHOD=get_bing
    if [ ! $DEFAULT ]; then METHOD=get_youdao; fi
    word=`echo $1 | tr [A-Z] [a-z]`
    query=`echo "${word}" | tr ' ' '+'`
    result=`$METHOD "$query" | sed 's/\./. /g'`
    if [ "$result" == "" ]
    then echo -e "\e[1;31mNo result found.\e[0m"
    else
        echo $result | sed 's/^@//' | tr '@' '\012'
        printf "%-30s%s\n" "${query}" "${result}" | sed 's/^@//' | tr '@' ' ' >> "${HOME}/Desktop/Voca"
    fi
}

get_bing(){
    curl -s http://cn.bing.com/dict/?q="$1" | grep -o '<ul><li><span class="pos.*">.*<\/span><\/li><\/ul>' | sed 's/<span class="pos web">网络<\/span><span class="def"><span>/@web: /' | sed -e 's/<span class="pos">/@/g' -e 's/<span class="pos web">//g' | sed 's/<span class="def">//g' | sed -e 's/span//g' -e 's/ul//g' -e 's/li//g' | tr -d '<>/'
}

get_youdao(){
    curl -s http://dict.youdao.com/w/eng/"$1"/ | sed -n '/<div class="trans-container">/,/<\/div>/p' | grep '<li>.*<\/li>' | sed -e 's/<\/\?li>//g' -e 's/ //g' | tr '\n' '@' | sed 's/@$//'
}

main(){
    SERVER="cn.bing.com"
    QUERY_SERVER="http://cn.bing.com/dict/"
    if [ ! $DEFAULT ]; then
        SERVER="dict.youdao.com"
        QUERY_SERVER="http://dict.youdao.com/w/";
    fi
    echo -en "\e[1;36mWait... not ready connected to the Server.\e[0m"
    start=`date +%s%N`
    time=`ping -c 1 -q $SERVER | tail -n 1 | awk 'BEGIN { FS="/" } { print $5 }'`
    mid=`date +%s%N`
    test=`curl -s $QUERY_SERVER`
    delta1=$((($mid - $start) / 1000000))
    delta2=$(((`date +%s%N` - $mid) / 1000000))
    if [ "${test}" ]; then
        echo -e "\r\e[1;31mReady to help you look up the word. Reach/Ping/Curl time: $delta1/$time/${delta2}ms.\e[0m"
    fi
    trap 'echo -e "\e[0m"; trap - INT; exit 2;' INT

    while true
    do
        random_color
        read word
        search_save "$word"
        echo -en "\e[0m"
        seperate_line
    done
}

# Parameter
export USAGE=
export COUNT=
export QUICK=
export DEBUG=
export DEFAULT=1

if [ "$1" ]
then
    while [ $@ ]; do
        case "$1" in
            -a) DEBUG=1  ;;
            -h) USAGE=1  ;;
            -c) COUNT=1  ;;
            -y) DEFAULT= ;;
            *) QUICK=1   ;;
        esac
        shift
    done
fi

if [ $USAGE ]; then usage
elif [ $COUNT ]; then echo "$(wc -l ~/Desktop/Voca | awk '{print $1}') words in total."
elif [ $DEBUG ]; then result=`curl -s http://cn.bing.com/dict/?q=${2} | grep -o '<ul><li><span class="pos">.*<\/span><\/li><\/ul>'`
elif [ $QUICK ]; then search_save "$1"
else main
fi
