#!/bin/bash

usage(){
    echo "Usage: enter ./dict to open search and enter any word you want, on press of"
    echo "[Enter], it will help you look up Bing and show it up."
    echo 
    echo "Or use parameter to give it a word as \"./dict \$word\"."
}

random_color(){
    g=$(($RANDOM % 255))
    f=$(($RANDOM % 255))
    b=$(($RANDOM % 255))
    echo -en "\x1b[38;2;${f};${g};${b}m"
}

test_web(){
    echo -en "\x1b[1;36mWait... not ready connected to the Internet.\x1b[0m"
    start1=`python -c 'import time; print int(time.time()*1000)'`
    time=`ping -c 1 -q cn.bing.com | tail -n 1 | awk ' BEGIN { FS="/" } { print $5 }'`
    end1=`python -c 'import time; print int(time.time()*1000)'`
    start2=`python -c 'import time; print int(time.time()*1000)'`
    test=`curl -s http://cn.bing.com/dict/`
    end2=`python -c 'import time; print int(time.time()*1000)'`
    delta1=$(($end1 - $start1))
    delta2=$(($end2 - $start2))
    if [ "${test}" ]
        then echo -e "\r\x1b[1;31mReady to help you look up the word. Reach/Ping/Curl time: ${delta1}/${time}/${delta2}ms.\x1b[0m"
    fi
}

seperate_line(){
    col=`echo $(tput cols)`
    for i in $(seq ${col})
    do
	    echo -n "-"
    done
    echo
}

search_save(){
    word=`echo $1 | tr [A-Z] [a-z]`
    query=`echo "${word}" | tr ' ' '+'`
    result=`curl -s http://cn.bing.com/dict/?q=${query} | grep -o '<ul><li><span class="pos.*">.*<\/span><\/li><\/ul>' | sed 's/<\/span><\/span><\/li><li><span class="pos web">网络<\/span><span class="def"><span>/@web: /' | sed 's/<ul><li><span class="pos"//' | sed 's/<span class="pos">/@/g' | sed 's/<span class="def">//g' | sed -e 's/span//g' -e 's/ul//g' -e 's/li//g' | tr -d '<>/'`
    if [ "$result" == "" ]
    then echo -e "\x1b[1;31mNo result found.\x1b[0m"
    else
        echo $result | tr '@' '\012'
        printf "%-30s%s\n" "${word}" "${result}" | tr '@' ' ' >> "${HOME}/Desktop/Voca"
    fi
}

main(){
    trap 'echo -e "\x1b[0m"; trap - INT; exit 2;' INT
    while true
    do
        random_color
        read word
        search_save $word
        echo -en "\x1b[0m"
        seperate_line
    done
}

# Parameter
if [ "$1" ]
then
    case "$1" in
        -a)
            result=`curl -s http://cn.bing.com/dict/?q=${2} | grep -o '<ul><li><span class="pos">.*<\/span><\/li><\/ul>'`
            ;;
        -h)
            usage
            ;;
        *)
            search_save $1
            ;;
    esac
else
    test_web
    main
fi
