#!/bin/bash

while true
do
    trap 'echo -e "\e[0m"; exit 1;' INT
    if [ $1 ]
    then
        if [ $1 != *-n* ]
        then
            g=$(($RANDOM % 255))
            f=$(($RANDOM % 255))
            b=$(($RANDOM % 255))
            echo -en "\e[38;2;${f};${g};${b}m"
        fi
        word=$1
    else read word
    fi
    result=`curl -s http://cn.bing.com/dict/?q=${word} | grep -o '<ul><li><span class="pos">.*<\/span><\/li><\/ul>' | sed 's/<\/span><\/span><\/li><li><span class="pos web">网络<\/span><span class="def"><span>/;/' | sed 's/<\/span><\/span><\/li><\/ul>//' | sed 's/<ul><li><span class="pos">.*<\/span><span class="def"><span>//'`
    echo $result
    echo -en "\e[0m"
    if [ $1 ]
    then break
    else echo '--------------------------------------------------------------------------------'
    fi
done
trap - INT
